# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0002_leaderboards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboards',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='leaderboards',
            name='user_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
