# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0003_auto_20160611_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offence_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('offence_type', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackbot.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Leaderboards',
        ),
    ]
