# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0006_auto_20160611_1120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offence_Log',
            new_name='OffenceLog',
        ),
    ]
