# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0008_auto_20160614_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=30),
        ),
    ]
